---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: datawire/hello-kubernetes:1.0
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
        ports:
        - name: http-api
          containerPort: 5000
